### ISSUE TITLE
zodiac sign detection problem

### ISSUE THREAD

**Issue by Maxatma** [emvakar/EKAstrologyCalc#17]
Not working zodiac sign detection. 
`getMoonZodicaSign`
Not sure why, but seems like Zodiac is detected wrongly by date passed like 20.07 should be cancer, but it is libra somewhy. But maybe it shouldn't work like that. Please, tell me if I misunderstood 

Also, there is obvious mistake in this switch :
```
if (longitude < 33.18) {
            zodiac = .aries
        } else if (longitude < 51.16) {
            zodiac = .cancer
        } else if (longitude < 93.44) {
            zodiac = .gemini
        } else if (longitude < 119.48) {
            zodiac = .cancer
        } else if (longitude < 135.30) {
            zodiac = .leo
        } else if (longitude < 173.34) {
            zodiac = .virgo
        } else if (longitude < 224.17) {
            zodiac = .libra
        } else if (longitude < 242.57) {
            zodiac = .scorpio
        } else if (longitude < 271.26) {
            zodiac = .sagittarius
        } else if (longitude < 302.49) {
            zodiac = .capricorn
        } else if (longitude < 311.72) {
            zodiac = .aquarius
        } else if (longitude < 348.58) {
            zodiac = .pisces
        } else {
            zodiac = .aries
        }
```
it contains Cancer twice, but no Taurus
good luck with improving your library

**Comment by emvakar** [comment]
@Maxatma wow, I'll watch this in the morning and write a comment

**Comment by emvakar** [comment]
@Maxatma Hello, about 20.07, on this day the moon has several zadiac signs, depending on the date sent, the sign in the moon will be calculated.

In my position Moscow, the sign for this day is calculated correctly at different times. Please try to write a test for your coordinates and time, and I will double-check everything, thanks

> Also, there is obvious mistake in this switch :
> 
> if (longitude < 33.18) {
>             zodiac = .aries
>         } else if (longitude < 51.16) {
>             zodiac = .cancer
>         } else if (longitude < 93.44) {
>             zodiac = .gemini
>         } else if (longitude < 119.48) {
>             zodiac = .cancer
>         } else if (longitude < 135.30) {
>             zodiac = .leo
>         } else if (longitude < 173.34) {
>             zodiac = .virgo
>         } else if (longitude < 224.17) {
>             zodiac = .libra
>         } else if (longitude < 242.57) {
>             zodiac = .scorpio
>         } else if (longitude < 271.26) {
>             zodiac = .sagittarius
>         } else if (longitude < 302.49) {
>             zodiac = .capricorn
>         } else if (longitude < 311.72) {
>             zodiac = .aquarius
>         } else if (longitude < 348.58) {
>             zodiac = .pisces
>         } else {
>             zodiac = .aries
>         }
> it contains Cancer twice, but no Taurus
> good luck with improving your library

I corrected it(only in spm), thanks for noticing
