### ISSUE TITLE
Is it possible to get a moon illumination ?

### ISSUE THREAD

**Issue by mongkonsrisin** [emvakar/EKAstrologyCalc#21]
How to get a moon illumination in Double (illuminated fraction of the moon; varies from 0.0 (new moon) to 1.0 (full moon) ) ?

**Comment by emvakar** [comment]
@mongkonsrisin 
I apologize for the long delay, I got added today

```swift
public struct EKIllumination {
    
    let fraction: Double
    let phase: Double
    let angle: Double
}
```
phase from 0 to 1
